// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/advance/{department}": {
            "post": {
                "description": "将用户排序提前一位。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员叫号接口"
                ],
                "summary": "提前",
                "parameters": [
                    {
                        "description": "changeInfo",
                        "name": "changeInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entiy.ChangeInfo"
                        }
                    },
                    {
                        "type": "string",
                        "description": "department",
                        "name": "department",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{OK}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{Not Found}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/applyLine": {
            "get": {
                "description": "获取报名信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员叫号接口"
                ],
                "summary": "获取报名信息",
                "responses": {
                    "200": {
                        "description": "{OK}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{Not Found}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/delay/{department}": {
            "post": {
                "description": "将用户排序延后一位。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员叫号接口"
                ],
                "summary": "延后",
                "parameters": [
                    {
                        "description": "changeInfo",
                        "name": "changeInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entiy.ChangeInfo"
                        }
                    },
                    {
                        "type": "string",
                        "description": "department",
                        "name": "department",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{OK}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{Not Found}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/delete/{department}": {
            "post": {
                "description": "删除用户排队。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员叫号接口"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "description": "changeInfo",
                        "name": "changeInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entiy.ChangeInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{OK}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{Not Found}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/line/{department}": {
            "get": {
                "description": "根据部门，获取对应排队列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员叫号接口"
                ],
                "summary": "获取排队列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "department",
                        "name": "department",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{OK}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{Not Found}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/next/{department}": {
            "get": {
                "description": "根据部门，更新状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员叫号接口"
                ],
                "summary": "下一位",
                "parameters": [
                    {
                        "type": "string",
                        "description": "department",
                        "name": "department",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{OK}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{Not Found}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/order": {
            "post": {
                "description": "根据学号判断用户是否已报名，已报名的才可以预约。。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提交信息接口"
                ],
                "summary": "面试预约",
                "parameters": [
                    {
                        "description": "orderInfo",
                        "name": "apply",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entiy.OrderInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{OK}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{Not Found}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/reset": {
            "post": {
                "description": "将用户从已结束状态从新插入队列（防止管理端误差）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员叫号接口"
                ],
                "summary": "重置",
                "parameters": [
                    {
                        "description": "waitInfo",
                        "name": "waitInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entiy.WaitInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{OK}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{Not Found}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/student/apply": {
            "post": {
                "description": "填写报名信息，根据学号判断用户是否曾经报名过。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提交信息接口"
                ],
                "summary": "纳新报名",
                "parameters": [
                    {
                        "description": "applyInfo",
                        "name": "apply",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entiy.ApplyInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{OK}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{Not Found}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/student/login": {
            "post": {
                "description": "确定用户学号。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提交信息接口"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "loginInfo",
                        "name": "apply",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entiy.LoginInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{OK}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{Not Found}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/student/wait": {
            "post": {
                "description": "查看前面等待人数。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提交信息接口"
                ],
                "summary": "等待人数",
                "parameters": [
                    {
                        "description": "waitInfo",
                        "name": "apply",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entiy.WaitInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{OK}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{Not Found}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entiy.ApplyInfo": {
            "type": "object",
            "properties": {
                "Department1": {
                    "type": "string"
                },
                "Department2": {
                    "type": "string"
                },
                "PhoneNum": {
                    "type": "string"
                },
                "StuName": {
                    "type": "string"
                },
                "StuNum": {
                    "type": "string"
                }
            }
        },
        "entiy.ChangeInfo": {
            "type": "object",
            "properties": {
                "Department": {
                    "type": "string"
                },
                "StuNum": {
                    "type": "string"
                }
            }
        },
        "entiy.LoginInfo": {
            "type": "object",
            "properties": {
                "PhoneNum": {
                    "type": "string"
                },
                "StuName": {
                    "type": "string"
                },
                "StuNum": {
                    "type": "string"
                }
            }
        },
        "entiy.OrderInfo": {
            "type": "object",
            "properties": {
                "Department1": {
                    "type": "string"
                },
                "Department2": {
                    "type": "string"
                },
                "StuNum": {
                    "type": "string"
                }
            }
        },
        "entiy.WaitInfo": {
            "type": "object",
            "properties": {
                "Department": {
                    "type": "string"
                },
                "StuNum": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "桑梓纳新后端接口(go版本)",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
